### ISSUE TITLE
PyPi updates?

### ISSUE THREAD

**Issue by Cameleopardus** [fiorix/cyclone#168]
Is there a possibility of one of the maintainers pushing an update to the version on PyPi?

**Comment by posita** [comment]
:+1: It looks like there hasn't been a release in [over 2 years](https://github.com/fiorix/cyclone/tree/v1.1) despite [more than a few key updates](https://github.com/fiorix/cyclone/commits/master). :cry:

**Comment by fiorix** [comment]
Yeah I have to do that. Will wait for #169 then make a new release.

**Comment by posita** [comment]
:bulb: Consider also merging #165.

**Comment by posita** [comment]
...and #164.

**Comment by vltr** [comment]
@fiorix: does [this](https://github.com/fiorix/cyclone/pull/165#issuecomment-148364098) makes sense for a new release?

**Comment by vltr** [comment]
@fiorix : is python 2.5 support dropped? running trial it fails after only 18 tests.

```
$ python --version
Python 2.5.6

$ pip freeze
Twisted==12.0.0
mock==0.8.0
simplejson==3.8.0
ssl==1.16
wsgiref==0.1.2
zope.interface==3.5.3
```

PS: in a random shot, these are the packages and versions that could be installed with python 2.5.

**Comment by fiorix** [comment]
I think we should drop it, but since I haven't used it in a while, will let others chime in.

**Comment by vltr** [comment]
alright then, i'll just make sure the unit tests runs on 2.6, 2.7 and pypy

**Comment by posita** [comment]
:+1: for dropping 2.5 support.

Supporting 2.5 makes it [much harder to maintain a Python 2/3 compatible code base](http://lucumr.pocoo.org/2011/1/22/forwards-compatible-python/). Even 2.6 has oddities that need to be worked-around, but at least there's hope. Also, Twisted's latest releases require *at least* 2.7.

**Comment by vltr** [comment]
yeah, i really try to use everything described here
http://python-future.org/compatible_idioms.html , but if in 2.6 some things
are hard to workaround also, 2.5 is ... oh, well, goodbye 2.5 :)

**Comment by vltr** [comment]
@fiorix @posita @dpnova [I have created the option to set the json codec cyclone-wise and applied proposed changes from #165 and #170](https://github.com/vltr/cyclone/tree/master). Also, #170 had no unit test so I created one and fixed the unit test from #165 because it was breaking on PyPy. Got all tests working in PyPy 2.6.1, CPython 2.6.9 and 2.7.10. I'm not opening a PR for now because I would like your thoughts and considerations first :)

**Comment by posita** [comment]
@vltr, if I understand correctly, if a PR were to be created from your fork, it would obsolete #165 and #170, as well as expand the concept of a replaceable JSON parser to be system-wide (instead of being [RPC-only](https://github.com/fiorix/cyclone/pull/165#issuecomment-140726885)), as well as fill in the testing gaps? If I understood correctly, then that sounds good to me. :+1:

I can't speak for @dpnova and #165, but if you do create a PR, please @-mention me and put in the initial comment somewhere that it obsoletes #170 (so I can update that PR).

**Comment by vltr** [comment]
@posita yes, you understood correctly. since all those are somehow intertwined (to json codecs), i have put them all together. i already mentioned #165 and #170 in logs, but surely i'll mention everyone that led me to do this :)

**Comment by dpnova** [comment]
I think the time to do a release is coming soon, largely as some new security stuff is sitting in master now (disabled sslv3 for email client).

As it's been a while since we've had any discussion, can anyone raise any outstanding concerns they have here? I'll start gathering release notes and any other bits and pieces for it and discuss with @fiorix

**Comment by dpnova** [comment]
For me, #165 is something I'd like to accept. But it is my own PR so I'd appreciate a review from someone else, perhaps @vltr or @posita ?

**Comment by vltr** [comment]
@dpnova: see [this comment](https://github.com/fiorix/cyclone/issues/168#issuecomment-148773006), right up above. Does it makes sense?

**Comment by vltr** [comment]
I think we made parallel workings (after you incremented and got into the Pypy json gotcha), heh. But, where's @fiorix? I even sent him an email and there's just silence in the radio ...

**Comment by dpnova** [comment]
Ah he is busy working with Go most of the time now I think. We use cyclone in a lot of places at work so we're happy to help with it.. I'll discuss with him and outline some proposals for community involvement etc so we can move on issues quickly and keep releases regular. Stay tuned :)

**Comment by dpnova** [comment]
I don't have a big problem with the implementation, but I would rather keep the different aspects of it in different PR's. Do you happen to have feature branches anywhere with the stuff in it? No biggie if you don't.. just would make things easier.

Also I've got some tests in my feature branch.. might be worth making sure there's nothing we'll lose by binning that PR.

Also on another note, I think the next pypi release should initially be a beta so we can catch any issues there before doing a full final pypi release.

**Comment by posita** [comment]
:+1: for waiting for #165 (or similar functionality) before bumping the version number and pushing to PyPi. But, just to be clear, merging #165 *appears* to remove support for 2.6. Personally, I'm fine with that, especially given recent comments #171, but since @vltr asked about 2.5 previously, I thought I'd mention it.

**Comment by dpnova** [comment]
I removed 2.6 there, but to be clear I knew we were moving to tox which would have a proper dep matrix for testing etc. The 2.6 is removed there because the version of twisted we were testing against didn't support it any longer.

**Comment by vltr** [comment]
@posita, @dpnova: well, I know places where cyclone is still running against python 2.6, specially boxes based on RHEL 6. Besides that, I've been using just Python 2.7 AND I also have a local branch of cyclone ported to Python 3, but I haven't passed all tests yet, plus there's plenty of room for improvement (the performance is way behind master).

@dpnova: I agree with you about a PR for every aspect, that's why I didn't made one. Just merged code, implemented some tests and left it in my repo for review and discussion. I also agree about making the next release a beta, and if I may, can we schedule a meeting or something (IRC?) to talk about these new features, beta testing and some other stuff I've been wondering (and stocking) about (C speedups, etc) ? :)

**Comment by dpnova** [comment]
@vltr I'm in #cyclone on freenode all the time...

AFAIK 2.6 is still part of @evilaliv3's tox changes in #172 , so once we're happy with them 2.6 will be back into the mix.

**Comment by vltr** [comment]
:+1: 

let's continue on freenode :)

**Comment by vltr** [comment]
well ... it's been a long time. @dpnova @fiorix how should we consider this project? dead?

**Comment by fiorix** [comment]
I haven't written any new code in a good while. Wouldn't say dead because people use it in production and it's proven to be very stable and reliable.

**Comment by vltr** [comment]
@fiorix yeah, well, I have some in production too. i'm sorry i didn't made myself clear; i was questioning the development and future of cyclone, that's all :wink:

**Comment by fiorix** [comment]
Yeah I get it... and yes, no plans for me. Haven't actually written any serious Python in a while and not planning to.

**Comment by vltr** [comment]
i am sad to read this (about the project), but all I can do is thank you for everything, cyclone has been my choice since it appeared as an article of how twisted could have been used in tornado, if i recall 2010 or 2011. anyway, would you mind passing it forward for those that have plans and do want to implement new features on cyclone? i mean no one in specific, but a group of developers ...

**Comment by fiorix** [comment]
Sure, no problem at all. Recently did this with https://github.com/fiorix/txmongo, which is now owned by the twisted group. Notice it'll redirect to /twisted/txmongo. ;)

**Comment by vltr** [comment]
thanks again! well, its been a while since i had talks with the twisted guys, i don't know if they would have interest on cyclone or if @dpnova and others may want to create a group. what do you think?

**Comment by fiorix** [comment]
Who knows.. I like it better than `twisted.web`, which at the time I started cyclone (back in 09) did not support `@inlineCallbacks` and forced you to write spaghetti code.

**Comment by vltr** [comment]
well, yup, that sounds about right for me too ...

**Comment by dpnova** [comment]
We're using it everywhere in production too. that being said I would be
:+1: on twisted project custodianship, my main concern is we're not quite
at the standard required there (test coverage etc)

I guess it would be interesting to see what @glyph thinks. I'll ping him on
irc today.

On 15 Sep 2016 12:19 AM, "Richard K" <notifications@github.com> wrote:

well, yup, that sounds about right for me too ...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fiorix/cyclone/issues/168#issuecomment-247028030>, or mute
the thread

**Comment by vltr** [comment]
@dpnova yeah, that would be awesome :beers: ! i'll wait for news in here :wink:

**Comment by fiorix** [comment]
There's also `python-cyclone` on ubuntu. Been there for a while.

**Comment by glyph** [comment]
I'm not opposed to @twisted adopting this, but the way we presently do review workflow does not mean that Twisted Matrix Labs members are necessarily going to see and act upon feedback here.  However, making it so that they at least *could* do so would at least open the doors to more maintenance :).

**Comment by dpnova** [comment]
@glyph - I'll do a brief proposal of how I think it could work and what the gaps are from my point of view. "Gaps" meaning things I think need to be in place for the project to be twisted acceptable and gaps in terms of features, functionality bugs (py3 etc etc).

I will create an issue to continue this discussion.

Thanks everyone!

**Comment by fiorix** [comment]
👍

**Comment by vltr** [comment]
@fiorix just for the record, about the `python-cyclone` package on ubuntu ... you're right, but i think it comes from debian:

```
Format: 3.0 (quilt)
Source: python-cyclone
Binary: python-cyclone
Architecture: all
Version: 1.1-1
Maintainer: Jérémy Bobbio <lunar@debian.org>
Homepage: http://cyclone.io/
Standards-Version: 3.9.4
Vcs-Browser: http://anonscm.debian.org/gitweb/?p=collab-maint/python-cyclone.git
Vcs-Git: git://anonscm.debian.org/git/collab-maint/python-cyclone.git
Build-Depends: debhelper (>= 8), python-all (>= 2.6.6-3~), python-setuptools, python-twisted
Package-List: 
 python-cyclone deb python extra
```

No patches, straight from git.

**Comment by fiorix** [comment]
Following up from #183 here as well.

Today I added deploy configs via travis->PyPI and cut a new tag release v1.2.

**Comment by fiorix** [comment]
Python 2.7 worked fine and pushed to PyPI. The pypy test failed and I removed it from .travis.yml; if someone's willing to make all tests pass for Python 3 I'm happy to review and merge.
