### ISSUE TITLE
Run cyclone in multiple processes or threads?

### ISSUE THREAD

**Issue by hoavt-54** [fiorix/cyclone#180]
Hi, I run my server this way:

```
from twisted.internet import reactor
reactor.listenTCP(8887, Application(), interface="0.0.0.0")
reactor.run()
```

However, as I observed, requests are processed one at a time. The server takes up only around 6% of CPU and the clients need to wait very long. May I ask you where/which parameter I can change to increase the concurrent connections? 
Thanks.

**Comment by fiorix** [comment]
I suspect that this isn't related to cyclone itself, but rather something you might be doing in your application handler. Seen this before where people create new database connections and do other blocking operations in their handlers instead of keeping it async top to bottom.

**Comment by hoavt-54** [comment]
Thank you @fiorix. I did exactly what you suspected. However, I am not really sure about what you meant by "async top to bottom". Could you give me an example? 
Thank you very much.

**Comment by fiorix** [comment]
You shouldn't create database connections in your request handlers. Instead, you should create them when your application is instantiated and then reuse them as much as possible. Specifically for databases, check out [twisted.enterprise.adbapi](https://twistedmatrix.com/documents/16.5.0/core/howto/rdbms.html).

By "keep it async from top to bottom" I mean don't do any operation that can potentially block your request handler because your web server is running single threaded and must handle requests concurrently without blocking. If you block in one request handler, you'll block the entire server.
